### ISSUE TITLE
SVGView crushing on android 

### ISSUE THREAD

**Issue by kislasi** [nativescript-community/ui-svg#1]
Im trying to work with SVGView on a new blank project and it crushes on android (iOS works fine):

steps to reproduce:

1.  create new **angular** project.
2. npm i @nativescript-community/ui-svg.
3. add any svg file into: app\assets folder.
4. on _app\app.component.ts_ add:
    import {registerElement} from '@nativescript/angular';
    import { SVGView } from '@nativescript-community/ui-svg/';
    registerElement('SVGView', () => SVGView);
5. on _app\home\home.component.html_ add:
    <SVGView blendingMode="lighten" width="100%" height="30%" src="~/assets/icon.svg" stretch="aspectFit" backgroundColor="transparent"></SVGView>

<ins>Android exception:</ins>
An uncaught Exception occurred on "main" thread.
Calling js method onDraw failed
Error: java.lang.NullPointerException: Attempt to read from field 'float com.caverock.androidsvg.SVG$Box.width' on a null object reference

StackTrace:
push.../node_modules/@nativescript-community/ui-svg/index.js.MySVGView.onDraw(file:///data/data/org.nativescript.testApp/files/app/vendor.js:92391:19)
	at com.tns.Runtime.callJSMethodNative(Native Method)
	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1302)
	at com.tns.Runtime.callJSMethodImpl(Runtime.java:1188)
	at com.tns.Runtime.callJSMethod(Runtime.java:1175)
	at com.tns.Runtime.callJSMethod(Runtime.java:1153)
	at com.tns.Runtime.callJSMethod(Runtime.java:1149)
	at com.tns.gen.android.view.View_vendor_92383_28_MySVGView.onDraw(View_vendor_92383_28_MySVGView.java:39)
	at android.view.View.draw(View.java:22350)
	at android.view.View.updateDisplayListIfDirty(View.java:21226)
	at android.view.View.draw(View.java:22081)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
	at android.view.View.updateDisplayListIfDirty(View.java:21217)
	at android.view.View.draw(View.java:22081)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
	at android.view.View.draw(View.java:22353)
	at android.view.View.updateDisplayListIfDirty(View.java:21226)
	at android.view.View.draw(View.java:22081)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
	at android.view.View.draw(View.java:22353)
	at android.view.View.updateDisplayListIfDirty(View.java:21226)
	at android.view.View.draw(View.java:22081)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
	at android.view.View.draw(View.java:22353)
	at android.view.View.updateDisplayListIfDirty(View.java:21226)
	at android.view.View.draw(View.java:22081)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
	at android.view.View.updateDisplayListIfDirty(View.java:21217)
	at android.view.View.draw(View.java:22081)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
	at android.view.View.updateDisplayListIfDirty(View.java:21217)
	at android.view.View.draw(View.java:22081)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
	at android.view.View.updateDisplayListIfDirty(View.java:21217)
	at android.view.View.draw(View.java:22081)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
	at android.view.View.updateDisplayListIfDirty(View.java:21217)
	at android.view.View.draw(View.java:22081)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
	at android.view.View.draw(View.java:22353)
	at com.android.internal.policy.DecorView.draw(DecorView.java:806)
	at android.view.View.updateDisplayListIfDirty(View.java:21226)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:559)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:565)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:642)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:4101)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3828)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3099)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1952)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8171)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:972)
	at android.view.Choreographer.doCallbacks(Choreographer.java:796)
	at android.view.Choreographer.doFrame(Choreographer.java:731)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7656)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
Caused by: java.lang.NullPointerException: Attempt to read from field 'float com.caverock.androidsvg.SVG$Box.width' on a null object reference
	at com.caverock.androidsvg.SVGAndroidRenderer.renderMask(SVGAndroidRenderer.java:4576)
	at com.caverock.androidsvg.SVGAndroidRenderer.popLayer(SVGAndroidRenderer.java:792)
	at com.caverock.androidsvg.SVGAndroidRenderer.popLayer(SVGAndroidRenderer.java:758)
	at com.caverock.androidsvg.SVGAndroidRenderer.render(SVGAndroidRenderer.java:1054)
	at com.caverock.androidsvg.SVGAndroidRenderer.render(SVGAndroidRenderer.java:340)
	at com.caverock.androidsvg.SVGAndroidRenderer.renderChildren(SVGAndroidRenderer.java:380)
	at com.caverock.androidsvg.SVGAndroidRenderer.render(SVGAndroidRenderer.java:668)
	at com.caverock.androidsvg.SVGAndroidRenderer.render(SVGAndroidRenderer.java:344)
	at com.caverock.androidsvg.SVGAndroidRenderer.renderChildren(SVGAndroidRenderer.java:380)
	at com.caverock.androidsvg.SVGAndroidRenderer.render(SVGAndroidRenderer.java:668)
	at com.caverock.androidsvg.SVGAndroidRenderer.render(SVGAndroidRenderer.java:344)
	at com.caverock.androidsvg.SVGAndroidRenderer.renderChildren(SVGAndroidRenderer.java:380)
	at com.caverock.androidsvg.SVGAndroidRenderer.render(SVGAndroidRenderer.java:668)
	at com.caverock.androidsvg.SVGAndroidRenderer.render(SVGAndroidRenderer.java:344)
	at com.caverock.androidsvg.SVGAndroidRenderer.renderChildren(SVGAndroidRenderer.java:380)
	at com.caverock.androidsvg.SVGAndroidRenderer.render(SVGAndroidRenderer.java:668)
	at com.caverock.androidsvg.SVGAndroidRenderer.render(SVGAndroidRenderer.java:344)
	at com.caverock.androidsvg.SVGAndroidRenderer.renderChildren(SVGAndroidRenderer.java:380)
	at com.caverock.androidsvg.SVGAndroidRenderer.render(SVGAndroidRenderer.java:625)
	at com.caverock.androidsvg.SVGAndroidRenderer.renderDocument(SVGAndroidRenderer.java:313)
	at com.caverock.androidsvg.SVG.renderToCanvas(SVG.java:540)
	... 69 more

**Comment by farfromrefug** [comment]
@kislasi can you share your svg?

**Comment by kislasi** [comment]
@farfromrefug, here it is:
`<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="72" height="72" viewBox="0 0 72 72"><defs><path id="oyx5a" d="M267 324c0-16.569 13.431-30 30-30 16.569 0 30 13.431 30 30 0 16.569-13.431 30-30 30-16.569 0-30-13.431-30-30z"/><path id="oyx5d" d="M297 317v14"/><path id="oyx5e" d="M304 324h-14"/><mask id="oyx5c" width="2" height="2" x="-1" y="-1"><path fill="#fff" d="M267 294h60v60h-60z"/><use xlink:href="#oyx5a"/></mask><filter id="oyx5b" width="95" height="96" x="250" y="277" filterUnits="userSpaceOnUse"><feOffset dx="1" dy="2" in="SourceGraphic" result="FeOffset1025Out"/><feGaussianBlur in="FeOffset1025Out" result="FeGaussianBlur1026Out" stdDeviation="2.8 2.8"/></filter></defs><g><g transform="translate(-262 -290)"><g><g filter="url(#oyx5b)"><use fill="none" stroke-opacity=".34" stroke-width="0" mask="url(&quot;#oyx5c&quot;)" xlink:href="#oyx5a"/><use fill="#575757" fill-opacity=".34" xlink:href="#oyx5a"/></g><use fill="#e10514" xlink:href="#oyx5a"/></g><g><g><use fill="#fff" fill-opacity="0" stroke="#fff" stroke-miterlimit="50" stroke-width="2" xlink:href="#oyx5d"/></g><g><use fill="#fff" fill-opacity="0" stroke="#fff" stroke-miterlimit="50" stroke-width="2" xlink:href="#oyx5e"/></g></g></g></g></svg>`

**Comment by farfromrefug** [comment]
@kislasi for some reason the android lib does not like your svg. removing ` xlink:href="#oyx5a"` from the `<use fill="none" stroke-opacity=".34" stroke-width="0" mask="url(&quot;#oyx5c&quot;)" xlink:href="#oyx5a"/>` makes it work. Cant do much about it for now.
However you can try and report it here https://github.com/BigBadaboom/androidsvg

**Comment by kislasi** [comment]
@farfromrefug this is NOT the issue.
look like SVG 1 and SVG 2 are both supported (no problems with xlink).
the problem is with mask attribute:
<use fill="none" stroke-opacity=".34" stroke-width="0" **mask="url(&quot;#oyx5c&quot;)"**
                         xlink:href="#oyx5a"/>
